### ISSUE TITLE
How does "e" mode work?

### ISSUE THREAD

**Issue by mkst** [lab313ru/rnc_propack_source#12]
Firstly, thanks for this, am using it to extract some RNC-compressed files in Space Station Silicon Valley (N64 ROM).

Some of the files appear to be compressed twice, i.e.

```sh
$ ./tools/rnc_propack_source/rnc_propack s bin/rnc_618480.bin
-= RNC ProPackED v1.4 [by Lab 313] (11/04/2018) =-
-----------------------------
RNC archive found: 0x000000 (004183/004305 bytes)
```

After extracting `bin/rnc_618480.bin` to `assets/bin/rnc_618480.bin`, I can see:
```sh
mark@DESKTOP-AOUBO9E:~/sssv$ ./tools/rnc_propack_source/rnc_propack s assets/bin/rnc_618480.bin
-= RNC ProPackED v1.4 [by Lab 313] (11/04/2018) =-
-----------------------------
RNC archive found: 0x000001 (000085/000160 bytes)
RNC archive found: 0x000057 (000047/003072 bytes)
RNC archive found: 0x000087 (000839/050440 bytes)
RNC archive found: 0x0003cf (001172/004262 bytes)
RNC archive found: 0x000864 (000141/000156 bytes)
RNC archive found: 0x0008f2 (000087/000114 bytes)
RNC archive found: 0x00094a (000026/000002 bytes)
RNC archive found: 0x000965 (000036/000010 bytes)
RNC archive found: 0x00098a (000026/000002 bytes)
RNC archive found: 0x0009a5 (000050/000024 bytes)
RNC archive found: 0x0009d8 (001634/006348 bytes)
RNC archive found: 0x00103b (000077/000086 bytes)
RNC archive found: 0x001089 (000033/002048 bytes)
RNC archive found: 0x0010ab (000036/000010 bytes)
```

However, I don't understand how to use the `e` functionality (had a quick glance at [main.c](https://github.com/lab313ru/rnc_propack_source/blob/master/main.c#L1699) and doesn't look like its fully implemented?)

```sh
mark@DESKTOP-AOUBO9E:~/sssv$ ./tools/rnc_propack_source/rnc_propack e assets/bin/rnc_618480.bin
-= RNC ProPackED v1.4 [by Lab 313] (11/04/2018) =-
-----------------------------
Wrong command line specified!
```

Obviously I can feed each offset from the search into unpack via `-i`, but that's extra steps that I'd like to avoid if possible ;)

**EDIT**

Realised I was using the binary that came in the repo rather than compiling main.c myself... think you can close this!

**Comment by lab313ru** [comment]
Could you download the latest release?

**Comment by mkst** [comment]
Per my edit, I was just being dumb. So going to close this. Sorry!

**Comment by lab313ru** [comment]
Anyway, you can download the compiled one from the latest release, it doesn't require to compile by yourself and includes the latest fixes

**Comment by mkst** [comment]
I might do that, will see how I get on with my project. Also noticed that compression is only partially matching for SSSV - 250 out of 263 files match, but 13 dont. Need to figure out whether it's me, but would be good to know whether you know if there are any implementation changes over the lifespan of RNC?

**Comment by lab313ru** [comment]
> I might do that, will see how I get on with my project. Also noticed that compression is only partially matching for SSSV - 250 out of 263 files match, but 13 dont. Need to figure out whether it's me, but would be good to know whether you know if there are any implementation changes over the lifespan of RNC?

readme.md contains information about different dictionary size for the Aladdin game. Maybe this is your case too, but with some different size.

**Comment by lab313ru** [comment]
Could you send me binaries of the "strange" RNC?

**Comment by mkst** [comment]
[rnc_461900.zip](https://github.com/lab313ru/rnc_propack_source/files/5939869/rnc_461900.zip)

Hi @lab313ru, please find attached example. This is
```
$ xxd ../old/rnc_461900.bin
00000000: 524e 4301 0000 55c0 0000 003d f99c ab38  RNC...U....=...8
00000010: 0002 8c80 7033 0002 0000 0022 0d00 4400  ....p3....."..D.
00000020: 0000 200c 00ba 00ff 5059 a28b b7e2 7fbd  .. .....PY......
00000030: 15ff 0bf1 0000 0000 0000 02a2 0100 0000  ................
00000040: 0000 0401 8027 80ff bdac fccf ad14 0c00  .....'..........
```
but when extracted and repacked it is the same size, but different content:
```
$ xxd ../new/rnc_461900.bin
00000000: 524e 4301 0000 55c0 0000 003b f99c cbe1  RNC...U....;....
00000010: 0002 8c80 6833 0002 0000 00d1 0040 0400  ....h3.......@..
00000020: 0000 c200 a00b 00ff 95a5 bab8 15ff 732b  ..............s+
00000030: fe17 a201 0000 0000 0044 0300 0000 0000  .........D......
00000040: 0802 006e c5ff dc8a ffb9 9582 0100 0000  ...n............
```

I will take a look to see if I can get it to match with different dictionary lengths.

**Comment by lab313ru** [comment]
Yeah, different content means different dict size. Could you also attach the game executable, so I'll find an exact size for the dictionary?

**Comment by mkst** [comment]
The game is [Space Station Silicon Valley](https://en.wikipedia.org/wiki/Space_Station_Silicon_Valley) - I cannot send you the ROM. 

I assume there is only code to decompress the RNC files - there would be no need for the game to contain compression code.

I haven't look hard enough yet, but assume I'll uncover something like [this](https://github.com/tobiasvl/rnc_propack/blob/master/SOURCE/MIPS/RNC_1.ASM) in the ROM.

**Comment by lab313ru** [comment]
> 
> 
> The game is [Space Station Silicon Valley](https://en.wikipedia.org/wiki/Space_Station_Silicon_Valley) - I cannot send you the ROM.
> 
> I assume there is only code to decompress the RNC files - there would be no need for the game to contain compression code.
> 
> I haven't look hard enough yet, but assume I'll uncover something like [this](https://github.com/tobiasvl/rnc_propack/blob/master/SOURCE/MIPS/RNC_1.ASM) in the ROM.

You don't understand. To decompress it also allocates memory for the dictionary. So, just looking at the decompression code will tell me what's the dict size.

**Comment by lab313ru** [comment]
Just found the rom. Let me check it.

**Comment by lab313ru** [comment]
I can't understand, which version or platform should I use? I can't find any RNC binary like you 've sent me in GBC or N64 roms.

**Comment by mkst** [comment]
The file I attached is at offset `0x461900` in the US version of the N64 ROM and is 79 bytes in length.

**Comment by lab313ru** [comment]
Bruteforced every dictionary size. no success in matching. But you should not worry about that. Unpacking in the game will still work ok. In addition, my tool have compressed these files better: 79 (original) vs 76 (my)

**Comment by mkst** [comment]
Yeah I tried a bunch of dictionary sizes without success.

Hah, I'm trying to get byte-perfect match, so I will have to keep investigating.

**Comment by mkst** [comment]
Sure it's over 5 years later, but I just got codex to have a look at the non-matching issue and it fixed it! https://github.com/lab313ru/rnc_propack_source/commit/2e658ff9f991665c739ea29e73110c454f7bd94c

**Comment by lab313ru** [comment]
Thanks!
https://github.com/lab313ru/rnc_propack_source/commit/499e8128f9a3890cb4d287a11608b3ae1e0df440
