### ISSUE TITLE
Original/new size count is not correct

### ISSUE THREAD

**Issue by AnthraxBass** [lab313ru/rnc_propack_source#2]
Hi, I've tested the packing functionality, and the actual size of the input file, does not equal the statistics, printed by program. 
Example attached below. 
![defect_file_sizes](https://user-images.githubusercontent.com/3393365/32904637-7b5c59e2-cb00-11e7-919f-5cc01d3765f3.png)

**Comment by lab313ru** [comment]
Does program unpack it correctly?
Problem is only in printable size?

Sent from my Windows 10 phone

From: ilya
Sent: Thursday, November 16, 2017 19:54
To: lab313ru/rnc_propack_source
Cc: Subscribed
Subject: [lab313ru/rnc_propack_source] Original/new size count is not correct(#2)

Hi, I've tested the packing functionality, and the actual size of the input file, does not equal the statistics, printed by program.
Example attached below.
defect_file_sizes.txt

**Comment by AnthraxBass** [comment]
Looks like it's not able to unpack, so it's not only statistics, seems to me. 
![cannotunpack](https://user-images.githubusercontent.com/3393365/32937069-8c1b67b2-cb7f-11e7-8df3-ffae864b39f8.png)

**Comment by lab313ru** [comment]
Can you try to repeat everything, and give me all command lines and files?
And compiled binary too, please. I’ll chek it

Sent from my Windows 10 phone

**Comment by AnthraxBass** [comment]
[propackBinaryAndSource.zip](https://github.com/lab313ru/rnc_propack_source/files/1482073/propackBinaryAndSource.zip)
[testingFileBeforeAndAfterPacking.zip](https://github.com/lab313ru/rnc_propack_source/files/1482074/testingFileBeforeAndAfterPacking.zip)

Sure, man. 
1. I have compiled propack locally under the following versions of Cygwin, BusyBox, and compiler: 
``` 
uname -a
CYGWIN_NT-10.0-WOW MYPCNAME 2.8.2(0.313/5/3) 2017-07-12 20:36 i686 GNU/Linux

busybox | head -1
BusyBox v1.22.1 (2015-11-10 11:07:12    ) multi-call binary.
echo; gcc --version; echo; g++ --version;

gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

g++ (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

gcc main.c -o propack
```
2. Packed the file like this: 
```
./propack p HelloWorld.exe HelloWorld.pkd
```
3. Tried to unpack like this, pretty basic stuff: 
```
./propack u HelloWorld.pkd HelloWorldUn.exe
```
I'm attaching here both the testing file and the propack binary.

**Comment by lab313ru** [comment]
Check new source code, please.

**Comment by AnthraxBass** [comment]
Can you please share MSVC2010 solution for this? I'm not able to build

**Comment by lab313ru** [comment]
> I'm not able to build

My source code doesn't require MSVC to build the project. Why you cannot build it?
I mean, you can build it even with gcc if you want.

**Comment by lab313ru** [comment]
?

**Comment by AnthraxBass** [comment]
Yes, sorry for late reply. 
The before\after numbers issue seems to be fixed, but the rnc binary crashes during the unpack procedure. 
I can later provide more details.

**Comment by lab313ru** [comment]
It would be great.

**Comment by lab313ru** [comment]
Check it now. I've fixed some bugs.
