### ISSUE TITLE
Mode 2 packing error

### ISSUE THREAD

**Issue by anatsvit** [lab313ru/rnc_propack_source#4]
Тестирование проводилось под Windows 10 x64
Компиляция MinGw64 командой "gcc main.c"
---------------
1.При unpack программа падала, искал место на котором падала нашел что это функция read_buf а точнее на вызове memmove, сама read_buf вызывалась в read_source_byte вот на этой строке
read_buf(&v->mem1[size_to_read], v->input, &v->input_offset, left_size);
2.Удалось запустить unpack на linux, но на linux не отработал pack (зато под Windows 10 pack работал), ошибка Segmentation fault под Linux, под Windows работает только метод 1, метод 2 не работает
3.Распаковав на linux, запаковал на Windows вставил в игру по тому же адресу и увидел артефакты в графике.
4.Сравнил оригинал (я приложил оригинал NJC.HEX - это RNC архив из игры Earthworm Jim взятый по адресу 0x20A704) и запакованный вариант методом 1, у оригинала размер 12112 байт, у запакованного программой 12085 байт.

[NewJunkCity_0x20A704.zip](https://github.com/lab313ru/rnc_propack_source/files/1851538/NewJunkCity_0x20A704.zip)

**Comment by anatsvit** [comment]
Скачал Visual Studio скомпилировал, unpack и pack m=1 работает нормально, pack m=2 программа падает, и по прежнему оригинальный rnc архив ([NewJunkCity_0x20A704.zip](https://github.com/lab313ru/rnc_propack_source/files/1851538/NewJunkCity_0x20A704.zip)) отличается от "распакованного и снова запакованного" программой, в игре в графике после вставки запакованного присутствуют артефакты.

**Comment by lab313ru** [comment]
Надо глянуть.

**Comment by lab313ru** [comment]
Да, действительно, по сравнению со сжатием, использованным в игре, есть различия с определённого момента. Скорее всего, это баг в моём коде.

**Comment by lab313ru** [comment]
В общем, чтобы получить идентичный размер упакованного архива, как в Джиме, нужно использовать ключ "-d 16384". Это размер словаря. Он в Джиме используется меньший, чем по-умолчанию.

А по поводу -m=2 - действительно, есть бага.

**Comment by lab313ru** [comment]
Fixed in: b38425e40e6a420dcba3b859151d18ec007f8c70
