### ISSUE TITLE
LICENSING

### ISSUE THREAD

**Issue by othias** [lab313ru/rnc_propack_source#6]
I'd like to use this in a project, (as opposed to dernc.c from http://www.yoda.arachsys.com/dk/utils.html ) since this seems more accurate and supports method 1 and 2. I'm wondering about the legality of doing that? is this considered public domain or something else?

Thanks

**Comment by lab313ru** [comment]
Rob Northen knows about this code and he has no claims about it.

Sure, you can use this code in any project you want. But it would be great if you leave some words about this project in your About:) if you want.

**Comment by othias** [comment]
Sure I will :)
Perhaps you should still include a LICENSE file to make it perfectly clear?
