### ISSUE TITLE
Dont open RCN files from UFO - Enemy Unknown (CD32)

### ISSUE THREAD

**Issue by altiereslima** [lab313ru/rnc_propack_source#8]
Dont open RCN files from UFO - Enemy Unknown (Amiga CD32)

This files:
[Desktop.zip](https://github.com/lab313ru/rnc_propack_source/files/3168648/Desktop.zip)

**Comment by lab313ru** [comment]
Thank you, I'll check it!

**Comment by lab313ru** [comment]
It finds RNC archive in `s` mode, but returns error code.
But it will unpack rnc archive with `-i=0x1C` option

**Comment by altiereslima** [comment]
Thank you,
And to pack?

**Comment by lab313ru** [comment]
`2pack is alive:)`

You're able to pack only data that starts from 0x1C offset. So, to make fully compatible data after packing, you should also fix the header. It contains some sizes and offsets. Sorry, I can't help you with that for now.

**Comment by altiereslima** [comment]
![images](https://user-images.githubusercontent.com/18044879/57604524-bbc03680-753a-11e9-993f-b9dff04739a1.jpg)
